[package]
name = "graphs-algorithms"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.9.2"

[dev-dependencies]
criterion = "0.7.0"

[[bench]]
name = "dfs_bench"
harness = false
